


POST http://localhost:3003/estudante HTTP/1.1
Content-Type: application/json

  { 

  "nome": "Ditertertreno da Silva  Sauro",       
   "email": "Dintrereto@gmail.com",
    "dataNasc":"01/01/1990",
     "turmaId" :"0.302643476637366",
    "hobbys": ["ler" , "patins" , "olhar" , "mar"]

   }


# { 
#     "nome": "Gabriel Martins", 
#     "email": "gabriel@gmail.com",
#     "dataNasc":"13/04/1983",
#     "turmaId" :"0.31302916523901625"
# }
###

GET http://localhost:3003/students HTTP/1.1
Content-Type: application/json


### 
// Criando turmas 
Post http://localhost:3003/turmas HTTP/1.1
Content-Type: application/json

{ 
    "nome": "Futuro"
}

### 
# turma modulos > 0 
GET http://localhost:3003/turmas/validas HTTP/1.1
Content-Type: application/json



### 

// Turmas  modulo = 0 
GET http://localhost:3003/turmas/invalidas HTTP/1.1
Content-Type: application/json


###

PUT http://localhost:3003/turmas HTTP/1.1
Content-Type: application/json

{ 
    "turmaId": "0.31302916523901625", 
    "nome": "Moreira" ,
    "modulo": "2"
}


### 
Post http://localhost:3003/estudanteHobby HTTP/1.1
Content-Type: application/json

{ 
    "estudanteId": "0001_EstudanteId_teste" ,
    "hobbyId": "101_hobbyId_teste"
}


###
POST http://localhost:3003/docente HTTP/1.1
Content-Type: application/json

  { 

  "nome": "profe",       
   "email": "profe@gmail.com",
    "data_nasc":"1990-01-01",
     "turma_id" :"0.302643476637366"
   }

