POST http://localhost:3003/students HTTP/1.1
Content-Type: application/json

{ 
    "nome": "Jose da Silva", 
    "email": "jose@gmail.com",
    "dataNasc":"01/01/1990",
    "turmaId" :"Vaighaun"
}


### 

GET http://localhost:3003/students HTTP/1.1
Content-Type: application/json


### 

Post http://localhost:3003/turmas HTTP/1.1

Content-Type: application/json

{ 
    "nome": "turma_vaughan",
}

